/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;
import clases.Producto;
import excepciones.ErrorEscrituraException;
import java.awt.Color;
import modelo.GestorInventario;
import javax.swing.JOptionPane;
/**
 *
 * @author valer
 */
public class EntradaMercancia extends javax.swing.JFrame {
    private Producto productoEncontrado=null;
    /**
     * Creates new form MenuInicio
     */
    public EntradaMercancia() {
        initComponents();
        btnRegistrar.setEnabled(false);
        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt){
                actualizarStockEstimadoEntrada();
            }
        });
        UiUtils.instalarSoloEnteros(txtCant);
    }

    public void actualizarStockEstimadoEntrada()
    {
        if(productoEncontrado==null)
        {
            return;
        }
        try
        {
            int cant= Integer.parseInt(txtCant.getText().trim());
            int stockEstimado= productoEncontrado.getStockActual()+cant;
            txtStockEstimado.setText(String.valueOf(stockEstimado));
        }
        catch(NumberFormatException e)
        {
            txtStockEstimado.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        lblTituloCodigo = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloCant = new javax.swing.JLabel();
        lblTituloCategoria = new javax.swing.JLabel();
        lblTituloMotivo = new javax.swing.JLabel();
        lblTituloStockActual = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtStockActual = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();
        btnRegistrar = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtStockEstimado = new javax.swing.JTextField();
        lblTituloStockDespues = new javax.swing.JLabel();
        btnBack = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnEntrada2.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        lblTituloCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCodigo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCodigo.setText("Código Producto");
        jPanel1.add(lblTituloCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloNombre.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloNombre.setText("Nombre del Producto");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        lblTituloCant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCant.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCant.setText("Cantidad a Ingresar");
        jPanel1.add(lblTituloCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblTituloCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCategoria.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCategoria.setText("Categoría");
        jPanel1.add(lblTituloCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        lblTituloMotivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloMotivo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloMotivo.setText("Motivo / Detalle");
        jPanel1.add(lblTituloMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        lblTituloStockActual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockActual.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockActual.setText("Stock Actual");
        jPanel1.add(lblTituloStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        txtCodigoProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(0, 0, 51));
        txtCodigoProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 30));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(237, 237, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 280, 30));

        txtStockActual.setEditable(false);
        txtStockActual.setBackground(new java.awt.Color(237, 237, 255));
        txtStockActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockActual.setForeground(new java.awt.Color(0, 0, 51));
        txtStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActualActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 280, 30));

        txtCategoria.setEditable(false);
        txtCategoria.setBackground(new java.awt.Color(237, 237, 255));
        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(0, 0, 51));
        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 280, 30));

        txtCant.setBackground(new java.awt.Color(255, 255, 255));
        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCant.setForeground(new java.awt.Color(0, 0, 51));
        txtCant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        jPanel1.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 30));

        txtMotivo.setEditable(false);
        txtMotivo.setBackground(new java.awt.Color(237, 237, 255));
        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(0, 0, 51));
        txtMotivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 510, 30));

        btnBuscar.setBackground(new java.awt.Color(237, 237, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 51));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 280, -1));

        btnRegistrar.setBackground(new java.awt.Color(237, 237, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 51));
        btnRegistrar.setText("Registrar Entrada");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 280, -1));

        btnLimpiar.setBackground(new java.awt.Color(237, 237, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 51));
        btnLimpiar.setText("Registrar Nueva Entrada");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 280, -1));

        jComboBox1.setBackground(new java.awt.Color(237, 237, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Devolución", "Traslado Sucursal", "Producto Nuevo", "Otros" }));
        jComboBox1.setOpaque(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 200, 30));

        txtStockEstimado.setEditable(false);
        txtStockEstimado.setBackground(new java.awt.Color(237, 237, 255));
        txtStockEstimado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockEstimado.setForeground(new java.awt.Color(0, 0, 51));
        txtStockEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockEstimadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockEstimado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 280, -1));

        lblTituloStockDespues.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockDespues.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockDespues.setText("Stock Estimado");
        jPanel1.add(lblTituloStockDespues, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        btnBack.setBackground(new java.awt.Color(237, 237, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 51));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal3.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
        btnBuscar.doClick();
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtStockEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockEstimadoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtCodigoProducto.setText("");
        txtNombre.setText("");
        txtStockActual.setText("");
        txtCategoria.setText("");
        txtCant.setText("");
        txtMotivo.setText("");
        txtStockEstimado.setText("");
        jComboBox1.setSelectedIndex(0);
        productoEncontrado=null;
        btnRegistrar.setEnabled(false);
      
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        producto no encontrado
        uno esta seguro de buscar el producto
        */
        String codigo= txtCodigoProducto.getText().trim();
        if(codigo.isEmpty())
        {
            Producto seleccionado = UiUtils.seleccionarProducto(this);
            if(seleccionado == null)
            {
                JOptionPane.showMessageDialog(this, "Ingrese o seleccione el código de un producto.");
                return;
            }
            txtCodigoProducto.setText(seleccionado.getCodigo());
            codigo = seleccionado.getCodigo();
        }
        buscarProductoPorCodigo(codigo);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void buscarProductoPorCodigo(String codigo)
    {
        GestorInventario gestorInventario= AppContext.getGestorInventario();
        productoEncontrado= gestorInventario.buscarPorCodigo(codigo);
        if(productoEncontrado==null)
        {
            JOptionPane.showMessageDialog(this, "Producto no encontrado: "+codigo, "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombre.setText("");
            txtCategoria.setText("");
            txtStockActual.setText("");
            txtStockEstimado.setText("");
            return;
        }
        txtNombre.setText(productoEncontrado.getNombre());
        txtCategoria.setText(productoEncontrado.getCategoria().name());
        txtStockActual.setText(String.valueOf(productoEncontrado.getStockActual()));
        txtCant.setText("");
        txtStockEstimado.setText("");
        btnRegistrar.setEnabled(true);
    }

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        entrada registrada correctamente
        */
        if(productoEncontrado==null)
        {
            JOptionPane.showMessageDialog(this, "Primero busque un producto.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String cantTexto= txtCant.getText().trim();
        if(cantTexto.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese la cantidad a ingresar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int cant;
        try
        {
            cant=Integer.parseInt(cantTexto);
            if(cant<=0)
            {
                throw new NumberFormatException();
            }
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero positivo.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog( this, "¿Está seguro que desea registrar la entrada de " + cant + " unidad(es) del producto \"" + productoEncontrado.getNombre() + "\"?","Confirmar Entrada",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(confirmacion != JOptionPane.YES_OPTION)
        {
            return;
        }

        String detalle= UiUtils.obtenerDetalleMovimiento(jComboBox1, txtMotivo, "Entrada de mercancía");
        try
        {
            GestorInventario gestor = AppContext.getGestorInventario();
            gestor.registrarEntrada(productoEncontrado.getCodigo(), cant, detalle);
            txtStockActual.setText(String.valueOf(productoEncontrado.getStockActual()));
            txtStockEstimado.setText("");
            JOptionPane.showMessageDialog(this, "Entrada registrada correctamente. \nNuevo Stock: "+productoEncontrado.getStockActual(), "Éxito Entrada Mercancía", JOptionPane.INFORMATION_MESSAGE);
            btnLimpiar.doClick();
        }
        catch(ErrorEscrituraException e)
        {
            JOptionPane.showMessageDialog(this, "Error al guardar el movimiento: "+e.getMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
        if(productoEncontrado==null)
        {
            return;
        }
        try
        {
            int cant= Integer.parseInt(txtCant.getText().trim());
            int stockEstimado= productoEncontrado.getStockActual()+cant;
            txtStockEstimado.setText(String.valueOf(stockEstimado));
            
        }
        catch(NumberFormatException e)
        {
            txtStockEstimado.setText("");
        }
    }//GEN-LAST:event_txtCantActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       UiUtils.configurarCampoDetalle(jComboBox1, txtMotivo);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaMercancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblTituloCant;
    private javax.swing.JLabel lblTituloCategoria;
    private javax.swing.JLabel lblTituloCodigo;
    private javax.swing.JLabel lblTituloMotivo;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloStockActual;
    private javax.swing.JLabel lblTituloStockDespues;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtStockEstimado;
    // End of variables declaration//GEN-END:variables
}
