/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import persistencia.ExportadorCSV;

/**
 *
 * @author valer
 */
public class ExportarInventario extends javax.swing.JFrame {

    private File carpetaSeleccionada;
    /**
     * Creates new form MenuInicio
     */
    public ExportarInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        lblTituloStockAntes = new javax.swing.JLabel();
        txtStockAntes = new javax.swing.JTextField();
        btnExportar = new javax.swing.JToggleButton();
        btnSeleccionCarpeta1 = new javax.swing.JToggleButton();
        lblTituloCarpetaSeleccionada = new javax.swing.JLabel();
        txtCarpetaSeleccionada = new javax.swing.JTextField();
        btnBack1 = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnExportar.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        lblTituloStockAntes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockAntes.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockAntes.setText("Archivo Destino: ");
        jPanel1.add(lblTituloStockAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 30));

        txtStockAntes.setEditable(false);
        txtStockAntes.setBackground(new java.awt.Color(237, 237, 255));
        txtStockAntes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtStockAntes.setForeground(new java.awt.Color(0, 0, 51));
        txtStockAntes.setText("inventario_completo.csv");
        txtStockAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockAntesActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 280, 30));

        btnExportar.setBackground(new java.awt.Color(237, 237, 255));
        btnExportar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(0, 0, 51));
        btnExportar.setText("Exportar CSV");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 280, 50));

        btnSeleccionCarpeta1.setBackground(new java.awt.Color(237, 237, 255));
        btnSeleccionCarpeta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSeleccionCarpeta1.setForeground(new java.awt.Color(0, 0, 51));
        btnSeleccionCarpeta1.setText("Selección de Carpeta");
        btnSeleccionCarpeta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionCarpeta1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionCarpeta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 280, 50));

        lblTituloCarpetaSeleccionada.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCarpetaSeleccionada.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCarpetaSeleccionada.setText("Carpeta Seleccionada:");
        jPanel1.add(lblTituloCarpetaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 30));

        txtCarpetaSeleccionada.setEditable(false);
        txtCarpetaSeleccionada.setBackground(new java.awt.Color(237, 237, 255));
        txtCarpetaSeleccionada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCarpetaSeleccionada.setForeground(new java.awt.Color(0, 0, 51));
        txtCarpetaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarpetaSeleccionadaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCarpetaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 240, 30));

        btnBack1.setBackground(new java.awt.Color(237, 237, 255));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(0, 0, 51));
        btnBack1.setText("Atrás");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal3.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        if(carpetaSeleccionada==null)
        {
            JOptionPane.showMessageDialog(this, "Primero selecciona una carpeta.");
            return;
        }
        try
        {
            AppContext.getGestorInventario().guardarInventarioCompleto();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el CSV antes de exportar: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        File archivoOrigen= new File(ExportadorCSV.ARCHIVO);
        File archivoDestino= new File(carpetaSeleccionada, archivoOrigen.getName());
        try
        {
            Files.copy(archivoOrigen.toPath(), archivoDestino.toPath(), StandardCopyOption.REPLACE_EXISTING);
            JOptionPane.showMessageDialog(this, "Archivo exportado a: "+archivoDestino.getAbsolutePath());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "No se pudo exportar el CSV: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void txtStockAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockAntesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockAntesActionPerformed

    private void btnSeleccionCarpeta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionCarpeta1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int resultado= fc.showOpenDialog(null);
        if(resultado==JFileChooser.APPROVE_OPTION)
        {
           carpetaSeleccionada= fc.getSelectedFile();
           txtCarpetaSeleccionada.setText(carpetaSeleccionada.getAbsolutePath());
            
            
        }
    }//GEN-LAST:event_btnSeleccionCarpeta1ActionPerformed

    private void txtCarpetaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarpetaSeleccionadaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCarpetaSeleccionadaActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack1;
    private javax.swing.JToggleButton btnExportar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JToggleButton btnSeleccionCarpeta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblTituloCarpetaSeleccionada;
    private javax.swing.JLabel lblTituloStockAntes;
    private javax.swing.JTextField txtCarpetaSeleccionada;
    private javax.swing.JTextField txtStockAntes;
    // End of variables declaration//GEN-END:variables
}
