/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;
import excepciones.ArchivoNoEncontradoException;
import excepciones.ErrorEscrituraException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.MovimientoInventario;
import persistencia.GestorPersistencia;
/**
 *
 * @author valer
 */
public class HistorialMovimientos extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public HistorialMovimientos() {
        initComponents();
        List<MovimientoInventario> todos= leerTodosMovimientos();
        cargarMovimientos(todos);
    }

    public void cargarMovimientos(List<MovimientoInventario> movimientos)
    {
        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (MovimientoInventario movimiento : movimientos) {
            modelo.addRow(new Object[]{movimiento.getFecha().toString().replace("T", " "), movimiento.getTipo(), movimiento.getCodigoProducto(), movimiento.getCantidad()});
        }
    }
    
    private List<MovimientoInventario> leerTodosMovimientos()
    {
        try
        {
            GestorPersistencia persistencia= new GestorPersistencia();
            return persistencia.leerLogMovimientos();
        }
        catch (ArchivoNoEncontradoException e)
        {
            JOptionPane.showMessageDialog(this, "No se encontró el archivo de movminetos", "AVISO", JOptionPane.INFORMATION_MESSAGE);
            return new java.util.ArrayList<>();
        }
        catch (ErrorEscrituraException e)
        {
            JOptionPane.showMessageDialog(this, "Error al leer el historial: "+e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            return new java.util.ArrayList<>();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JToggleButton();
        btnBuscar = new javax.swing.JToggleButton();
        Refresh = new javax.swing.JToggleButton();
        lblTituloFiltro = new javax.swing.JLabel();
        lblTotalProductos = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack1 = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnHistorial.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        jComboBox1.setBackground(new java.awt.Color(237, 237, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Entrada", "Salida", "Alertas" }));
        jComboBox1.setOpaque(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 280, 30));

        btnBack.setBackground(new java.awt.Color(237, 237, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 51));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(237, 237, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 51));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 290, -1));

        Refresh.setBackground(new java.awt.Color(237, 237, 255));
        Refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(0, 0, 51));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 280, -1));

        lblTituloFiltro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloFiltro.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloFiltro.setText("Filtro");
        jPanel1.add(lblTituloFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblTotalProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalProductos.setForeground(new java.awt.Color(0, 0, 51));
        lblTotalProductos.setText("Buscar Código Producto");
        jPanel1.add(lblTotalProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 51));
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(154, 154, 154)));
        txtCodigo.setCaretColor(new java.awt.Color(154, 154, 154));
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 280, 30));

        jTable1.setBackground(new java.awt.Color(255, 255, 234));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo", "Código", "Cantidad"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(237, 237, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 880, 220));

        btnBack1.setBackground(new java.awt.Color(237, 237, 255));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(0, 0, 51));
        btnBack1.setText("Atrás");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal3.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        -salida registrada correctamente
        -stock insuficiente
        */
        String filtroActual=jComboBox1.getSelectedItem().toString();
        List<MovimientoInventario> todos= leerTodosMovimientos();
        if(filtroActual.equals("Todos"))
        {
            cargarMovimientos(todos);
        }
        List<MovimientoInventario> filtrados= new ArrayList<>();
        for (MovimientoInventario movimiento : todos) 
        {
            if(movimiento.getTipo().equalsIgnoreCase(filtroActual))
            {
                filtrados.add(movimiento);
            }
        }
        cargarMovimientos(filtrados);
    }//GEN-LAST:event_RefreshActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String filtro= jComboBox1.getSelectedItem().toString();
        List<MovimientoInventario> todos= leerTodosMovimientos();
        if(filtro.equals("Todos"))
        {
            cargarMovimientos(todos);
            return;
        }
        List<MovimientoInventario> filtrados= new ArrayList<>();
        for (MovimientoInventario movimiento : todos) 
        {
            if(movimiento.getTipo().equalsIgnoreCase(filtro))
            {
                filtrados.add(movimiento);
            }
        }
        cargarMovimientos(filtrados);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codigo= txtCodigo.getText().trim();
        if(codigo.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un codigo", "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        List<MovimientoInventario> todos= leerTodosMovimientos();
        List<MovimientoInventario> resultados= new ArrayList<>();
        for (MovimientoInventario movimiento : todos) 
        {
            if(movimiento.getCodigoProducto().equalsIgnoreCase(codigo))
            {
                resultados.add(movimiento);
            }
        }
        if(resultados.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No se encontraron movimientos para código: "+codigo, "SIN RESULTADOS", JOptionPane.INFORMATION_MESSAGE);
        }
        cargarMovimientos(resultados);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Refresh;
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnBack1;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblTituloFiltro;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
