/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.awt.KeyboardFocusManager;
import java.awt.Window;
import java.util.Date;
import clases.*;
import Enums.CategoriaProducto;
import excepciones.*;
import modelo.GestorInventario;
import javax.swing.JOptionPane;
import javax.swing.JWindow;
import javax.swing.SwingUtilities;
import java.text.SimpleDateFormat;
/**
 *
 * @author valer
 */
public class RegistrarProducto extends javax.swing.JFrame {

    private boolean actualizandoFecha= false;
    /**
     * Creates new form MenuInicio
     */
    public RegistrarProducto() {
        initComponents();
        jPanelPerecedero.setVisible(true);
        jPanelElectronico.setVisible(false);
        jPanelMateriaPrima.setVisible(false);
        configurarListenersFecha();
    }

    public void configurarListenersFecha()
    {
        jDateChooser.getDateEditor().addPropertyChangeListener("date", evt -> {
        if(actualizandoFecha==true)
        {
            return;
        }
        Date fecha = jDateChooser.getDate();
        if (fecha != null) 
        {
            long diff = fecha.getTime() - new Date().getTime();
            long dias = diff / (1000 * 60 * 60 * 24);
            javax.swing.SwingUtilities.invokeLater(() -> {
                actualizandoFecha=true;
                try
                {
                    txtDiasVigencia.setText(String.valueOf(dias));
                }
                finally
                {
                    actualizandoFecha=false;
                }
            });
            
        }
    });

    // Días de vigencia → Fecha
    txtDiasVigencia.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

        private void calcularFecha() 
        {
            if (actualizandoFecha) 
            {
                return;
            }
            actualizandoFecha = true;
            try 
            {
                String texto = txtDiasVigencia.getText().trim();
                if (!texto.isEmpty()) 
                {
                    int dias = Integer.parseInt(texto);
                    java.util.Calendar cal = java.util.Calendar.getInstance();
                    cal.add(java.util.Calendar.DAY_OF_YEAR, dias);
                    
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        jDateChooser.setDate(cal.getTime());
                        actualizandoFecha=false;
                    });
                }
                else
                {
                    actualizandoFecha=false;
                }
            }
            catch (NumberFormatException ignored) 
            {
                actualizandoFecha= false;
            }
        }

        public void insertUpdate(javax.swing.event.DocumentEvent e) { calcularFecha(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { calcularFecha(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) {}
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        lblTituloCodigo = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloProveedor = new javax.swing.JLabel();
        lblTituloCategoría = new javax.swing.JLabel();
        lblPrecioUnitario = new javax.swing.JLabel();
        lblTituloStockInicial = new javax.swing.JLabel();
        lblTituloStockMinimo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        jPanelPerecedero = new javax.swing.JPanel();
        lblDiasVigencia = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        txtDiasVigencia = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        jPanelMateriaPrima = new javax.swing.JPanel();
        lblTituloUnidadMedida = new javax.swing.JLabel();
        lblTituloConcentracion = new javax.swing.JLabel();
        txtUnidadMedida = new javax.swing.JTextField();
        txtConcentracion = new javax.swing.JTextField();
        jPanelElectronico = new javax.swing.JPanel();
        lblTituloNumeroSerie = new javax.swing.JLabel();
        lblTituloGarantia = new javax.swing.JLabel();
        lblTituloVoltaje = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        txtGarantia = new javax.swing.JTextField();
        txtVoltaje = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JToggleButton();
        txtPrecio = new javax.swing.JTextField();
        txtStockInicial = new javax.swing.JTextField();
        txtStockMinimo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRegistro.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        lblTituloCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCodigo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCodigo.setText("Código Producto");
        jPanel1.add(lblTituloCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloNombre.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloNombre.setText("Nombre");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblTituloProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloProveedor.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloProveedor.setText("Proveedor");
        jPanel1.add(lblTituloProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        lblTituloCategoría.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCategoría.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCategoría.setText("Categoría");
        jPanel1.add(lblTituloCategoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        lblPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioUnitario.setForeground(new java.awt.Color(0, 0, 51));
        lblPrecioUnitario.setText("Precio Unitario");
        jPanel1.add(lblPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        lblTituloStockInicial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockInicial.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockInicial.setText("Stock Inicial");
        jPanel1.add(lblTituloStockInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        lblTituloStockMinimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockMinimo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockMinimo.setText("Stock Mínimo");
        jPanel1.add(lblTituloStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(237, 237, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perecedero", "Electrónico", "Materia Prima" }));
        jComboBox1.setOpaque(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 280, 30));

        txtCodigoProducto.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(0, 0, 51));
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 30));

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 30));

        txtProveedor.setBackground(new java.awt.Color(255, 255, 255));
        txtProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(0, 0, 51));
        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 280, 30));

        jPanelPerecedero.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPerecedero.setForeground(new java.awt.Color(245, 247, 255));
        jPanelPerecedero.setOpaque(false);
        jPanelPerecedero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiasVigencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDiasVigencia.setForeground(new java.awt.Color(0, 0, 51));
        lblDiasVigencia.setText("Días de Vigencia");
        jPanelPerecedero.add(lblDiasVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTemperatura.setForeground(new java.awt.Color(0, 0, 51));
        lblTemperatura.setText("Temperatura (°C)");
        jPanelPerecedero.add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFechaVencimiento.setForeground(new java.awt.Color(0, 0, 51));
        lblFechaVencimiento.setText("Fecha de Vencimiento");
        jPanelPerecedero.add(lblFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jDateChooser.setBackground(new java.awt.Color(237, 237, 255));
        jDateChooser.setForeground(new java.awt.Color(0, 0, 51));
        jPanelPerecedero.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, -1));

        txtDiasVigencia.setBackground(new java.awt.Color(255, 255, 255));
        txtDiasVigencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiasVigencia.setForeground(new java.awt.Color(0, 0, 51));
        txtDiasVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasVigenciaActionPerformed(evt);
            }
        });
        jPanelPerecedero.add(txtDiasVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 30));

        txtTemperatura.setBackground(new java.awt.Color(255, 255, 255));
        txtTemperatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTemperatura.setForeground(new java.awt.Color(0, 0, 51));
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });
        jPanelPerecedero.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        jPanel1.add(jPanelPerecedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, 230));

        jPanelMateriaPrima.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMateriaPrima.setForeground(new java.awt.Color(245, 247, 255));
        jPanelMateriaPrima.setOpaque(false);
        jPanelMateriaPrima.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloUnidadMedida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloUnidadMedida.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloUnidadMedida.setText("Unidad de Medida");
        jPanelMateriaPrima.add(lblTituloUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblTituloConcentracion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloConcentracion.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloConcentracion.setText("Concentración");
        jPanelMateriaPrima.add(lblTituloConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtUnidadMedida.setBackground(new java.awt.Color(255, 255, 255));
        txtUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnidadMedida.setForeground(new java.awt.Color(0, 0, 51));
        txtUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadMedidaActionPerformed(evt);
            }
        });
        jPanelMateriaPrima.add(txtUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 30));

        txtConcentracion.setBackground(new java.awt.Color(255, 255, 255));
        txtConcentracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConcentracion.setForeground(new java.awt.Color(0, 0, 51));
        txtConcentracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcentracionActionPerformed(evt);
            }
        });
        jPanelMateriaPrima.add(txtConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        jPanel1.add(jPanelMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 310, 230));

        jPanelElectronico.setBackground(new java.awt.Color(0, 0, 0));
        jPanelElectronico.setForeground(new java.awt.Color(245, 247, 255));
        jPanelElectronico.setOpaque(false);
        jPanelElectronico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloNumeroSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloNumeroSerie.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloNumeroSerie.setText("Número de Serie");
        jPanelElectronico.add(lblTituloNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblTituloGarantia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloGarantia.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloGarantia.setText("Garantía (meses)");
        jPanelElectronico.add(lblTituloGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTituloVoltaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloVoltaje.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloVoltaje.setText("Voltaje");
        jPanelElectronico.add(lblTituloVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtNumeroSerie.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroSerie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroSerie.setForeground(new java.awt.Color(0, 0, 51));
        txtNumeroSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroSerieActionPerformed(evt);
            }
        });
        jPanelElectronico.add(txtNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 30));

        txtGarantia.setBackground(new java.awt.Color(255, 255, 255));
        txtGarantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGarantia.setForeground(new java.awt.Color(0, 0, 51));
        txtGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarantiaActionPerformed(evt);
            }
        });
        jPanelElectronico.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        txtVoltaje.setBackground(new java.awt.Color(255, 255, 255));
        txtVoltaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVoltaje.setForeground(new java.awt.Color(0, 0, 51));
        txtVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoltajeActionPerformed(evt);
            }
        });
        jPanelElectronico.add(txtVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 30));

        jPanel1.add(jPanelElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, 230));

        btnLimpiar.setBackground(new java.awt.Color(237, 237, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 51));
        btnLimpiar.setText("Registrar Nuevo Producto");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 280, -1));

        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 51));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 280, 30));

        txtStockInicial.setBackground(new java.awt.Color(255, 255, 255));
        txtStockInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockInicial.setForeground(new java.awt.Color(0, 0, 51));
        txtStockInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockInicialActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 280, 30));

        txtStockMinimo.setBackground(new java.awt.Color(255, 255, 255));
        txtStockMinimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockMinimo.setForeground(new java.awt.Color(0, 0, 51));
        txtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMinimoActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 280, 30));

        btnRegistrar.setBackground(new java.awt.Color(237, 237, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 51));
        btnRegistrar.setText("Registrar Producto");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 280, -1));

        btnBack.setBackground(new java.awt.Color(237, 237, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 51));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal3.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void txtDiasVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasVigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasVigenciaActionPerformed

    private void txtVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoltajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoltajeActionPerformed

    private void txtGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarantiaActionPerformed

    private void txtNumeroSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSerieActionPerformed

    private void txtUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadMedidaActionPerformed

    private void txtConcentracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcentracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        //limpiar a Registrar nuevo producto
        txtCodigoProducto.setText("");
        txtNombre.setText("");
        txtProveedor.setText("");
        txtPrecio.setText("");
        txtStockInicial.setText("");
        txtStockMinimo.setText("");
        txtTemperatura.setText("");
        txtDiasVigencia.setText("");
        txtNumeroSerie.setText("");
        txtGarantia.setText("");
        txtVoltaje.setText("");
        txtUnidadMedida.setText("");
        txtConcentracion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jPanelPerecedero.setVisible(false);
        jPanelElectronico.setVisible(false);
        jPanelMateriaPrima.setVisible(false);
        if(jComboBox1.getSelectedItem().toString().equals("Perecedero"))
        {
            jPanelPerecedero.setVisible(true);
        }
        else if(jComboBox1.getSelectedItem().toString().equals("Electrónico"))
        {
            jPanelElectronico.setVisible(true);
        }
        else
        {
            jPanelMateriaPrima.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockInicialActionPerformed

    private void txtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMinimoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        producto registrado correctamente
        ya existe un producto con ese codigo
        datos inválidos
        */
        String codigo= txtCodigoProducto.getText().trim();
        String nombre= txtNombre.getText().trim();
        String proveedor= txtProveedor.getText().trim();
        String precioTxt= txtPrecio.getText().trim();
        String stockInicialTxt= txtStockInicial.getText().trim();
        String stockMinimoTxt= txtStockMinimo.getText().trim();
        if(codigo.isEmpty() || nombre.isEmpty() || proveedor.isEmpty() || precioTxt.isEmpty() || stockInicialTxt.isEmpty() || stockMinimoTxt.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Todos los campos comunes son obligatorios.", "AVISO", JOptionPane.WARNING_MESSAGE);
            return;
        }
        double precio;
        int stockInicial, stockMinimo;
        try
        {
            precio=Double.parseDouble(precioTxt);
            stockInicial= Integer.parseInt(stockInicialTxt);
            stockMinimo= Integer.parseInt(stockMinimoTxt);
            if(precio<0 || stockInicial<0 || stockMinimo<0)
            {
                throw new NumberFormatException();
            }
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Precio, Stock Inicial y Stock deben ser mayor o igual a 0.", "Datos Inválidos", JOptionPane.ERROR_MESSAGE);
            return;
        }

            String tipoSeleccionado = jComboBox1.getSelectedItem().toString();
        Producto nuevoProducto = null;

        try 
        {
            switch(tipoSeleccionado) 
            {
                case "Perecedero": 
                    Date fechaDate = jDateChooser.getDate();
                    if (fechaDate == null) 
                    {
                        cerrarPopupCalendario();
                        JOptionPane.showMessageDialog(this, "Seleccione la fecha de vencimiento.", "AVISO", JOptionPane.WARNING_MESSAGE);
                        jDateChooser.getDateEditor().getUiComponent().requestFocusInWindow();
                        return;
                    }
                    String fechaVencimiento= new SimpleDateFormat("yyyy-MM-dd").format(fechaDate);
                    String temperaturaTxt= txtTemperatura.getText().trim();
                    String diasTxt = txtDiasVigencia.getText().trim();
                    if (temperaturaTxt.isEmpty() || diasTxt.isEmpty()) 
                    {
                        JOptionPane.showMessageDialog(this, "Complete todos los campos de su Producto Perecedero.", "AVISO", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    double temperatura = Double.parseDouble(temperaturaTxt);
                    int diasVigencia = Integer.parseInt(diasTxt);
                    if(diasVigencia<0)
                    {
                        JOptionPane.showMessageDialog(this, "Los días de vigencia deben ser mayores a 0", "Datos Inválidos", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    nuevoProducto= new ProductoPerecible(fechaVencimiento, temperatura, diasVigencia, codigo, nombre, proveedor,CategoriaProducto.PERECEDERO, precio, stockInicial, stockMinimo);
                    break;
                case "Electrónico": 
                    String serie= txtNumeroSerie.getText().trim();
                    String garantiaTxt= txtGarantia.getText().trim();
                    String voltajeTxt= txtVoltaje.getText().trim();
                    if (serie.isEmpty() || garantiaTxt.isEmpty() || voltajeTxt.isEmpty()) 
                    {
                        JOptionPane.showMessageDialog(this, "Complete todos los campos de su Producto Electrónico.", "Aviso", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    int garantia = Integer.parseInt(garantiaTxt);
                    int voltaje = Integer.parseInt(voltajeTxt);
                    if(garantia<0 || voltaje<0)
                    {
                        JOptionPane.showMessageDialog(this, "Garantía y Voltaje deben ser mayor o igual a 0.", "Datos Inválidos", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    nuevoProducto = new ProductoElectronico(serie, garantia, voltaje,codigo, nombre, proveedor,CategoriaProducto.ELECTRONICO, precio, stockInicial, stockMinimo);
                    break;
                case "Materia Prima":
                    String unidad= txtUnidadMedida.getText().trim();
                    String concentracionTxt= txtConcentracion.getText().trim();
                    if (unidad.isEmpty() || concentracionTxt.isEmpty()) 
                    {
                        JOptionPane.showMessageDialog(this, "Complete todos los campos de su Materia Prima.", "Aviso", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    double concentracion= Double.parseDouble(concentracionTxt);
                    if(concentracion<0)
                    {
                        JOptionPane.showMessageDialog(this, "La concentración debe ser mayor o igual a 0.", "Datos Inválidos", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    nuevoProducto = new MateriaPrima(unidad, concentracion,codigo, nombre, proveedor,CategoriaProducto.MATERIA_PRIMA, precio, stockInicial, stockMinimo);
                    break;
                default:
                    break;
            }
        } 
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(this, "Verifique que los campos numéricos del tipo de producto sean válidos.", "Datos inválidos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog( this, "¿Está seguro que desea registrar el producto \"" + nombre + "\" [" + codigo + "] de tipo " + tipoSeleccionado + "?","Confirmar Registro",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE );
        if(confirmacion != JOptionPane.YES_OPTION)
        {
            return;
        }
        
        try 
        {
            GestorInventario gestor = AppContext.getGestorInventario();
            gestor.registrarProducto(nuevoProducto);
            gestor.guardarInventarioCompleto();
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "Producto registrado correctamente:\n" + nombre + " [" + codigo + "]\n\n¿Desea registrar otro producto de tipo " + tipoSeleccionado + "?",
                    "Éxito", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            btnLimpiar.doClick();//para que se limpie de un solo
            if(respuesta != JOptionPane.YES_OPTION)
            {
                this.dispose();
                new MenuInicio().setVisible(true);
            }
            else
            {
                txtCodigoProducto.requestFocus();
            }
        } 
        catch (ProductoDuplicadoException e) 
        {
            JOptionPane.showMessageDialog(this,"Ya existe un producto con el código: " + codigo,"Código duplicado", JOptionPane.ERROR_MESSAGE);
        } 
        catch (DatosInvalidosInventarioException e) 
        {
            JOptionPane.showMessageDialog(this, "Datos inválidos: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        catch (ErrorEscrituraException e)
        {
            JOptionPane.showMessageDialog(this, "El producto se agregó, pero no se pudo guardar en disco: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cerrarPopupCalendario()
    {
        KeyboardFocusManager.getCurrentKeyboardFocusManager().clearGlobalFocusOwner();
        for(Window ventana : Window.getWindows())
        {
            if(ventana instanceof JWindow && ventana.isShowing())
            {
                ventana.setVisible(false);
            }
        }
        SwingUtilities.invokeLater(() -> btnRegistrar.requestFocusInWindow());
    }

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelElectronico;
    private javax.swing.JPanel jPanelMateriaPrima;
    private javax.swing.JPanel jPanelPerecedero;
    private javax.swing.JLabel lblDiasVigencia;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblPrecioUnitario;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTituloCategoría;
    private javax.swing.JLabel lblTituloCodigo;
    private javax.swing.JLabel lblTituloConcentracion;
    private javax.swing.JLabel lblTituloGarantia;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloNumeroSerie;
    private javax.swing.JLabel lblTituloProveedor;
    private javax.swing.JLabel lblTituloStockInicial;
    private javax.swing.JLabel lblTituloStockMinimo;
    private javax.swing.JLabel lblTituloUnidadMedida;
    private javax.swing.JLabel lblTituloVoltaje;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtConcentracion;
    private javax.swing.JTextField txtDiasVigencia;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtStockInicial;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtUnidadMedida;
    private javax.swing.JTextField txtVoltaje;
    // End of variables declaration//GEN-END:variables
}
