/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.util.Date;

/**
 *
 * @author valer
 */
public class RegistrarProducto extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public RegistrarProducto() {
        initComponents();
        jPanelPerecedero.setVisible(true);
        jPanelElectronico.setVisible(false);
        jPanelMateriaPrima.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        lblTituloCodigo = new javax.swing.JLabel();
        lblTituloNombre = new javax.swing.JLabel();
        lblTituloProveedor = new javax.swing.JLabel();
        lblTituloCategoría = new javax.swing.JLabel();
        lblPrecioUnitario = new javax.swing.JLabel();
        lblTituloStockInicial = new javax.swing.JLabel();
        lblTituloStockMinimo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        jPanelPerecedero = new javax.swing.JPanel();
        lblDiasVigencia = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        txtDiasVigencia = new javax.swing.JTextField();
        txtTemperatura = new javax.swing.JTextField();
        jPanelMateriaPrima = new javax.swing.JPanel();
        lblTituloUnidadMedida = new javax.swing.JLabel();
        lblTituloConcentracion = new javax.swing.JLabel();
        txtUnidadMedida = new javax.swing.JTextField();
        txtConcentracion = new javax.swing.JTextField();
        jPanelElectronico = new javax.swing.JPanel();
        lblTituloNumeroSerie = new javax.swing.JLabel();
        lblTituloGarantia = new javax.swing.JLabel();
        lblTituloVoltaje = new javax.swing.JLabel();
        txtNumeroSerie = new javax.swing.JTextField();
        txtGarantia = new javax.swing.JTextField();
        txtVoltaje = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JToggleButton();
        txtPrecio = new javax.swing.JTextField();
        txtStockInicial = new javax.swing.JTextField();
        txtStockMinimo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnRegistro.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        btnBack.setBackground(new java.awt.Color(237, 237, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 51));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        lblTituloCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCodigo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCodigo.setText("Código Producto");
        jPanel1.add(lblTituloCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblTituloNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloNombre.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloNombre.setText("Nombre");
        jPanel1.add(lblTituloNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblTituloProveedor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloProveedor.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloProveedor.setText("Proveedor");
        jPanel1.add(lblTituloProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        lblTituloCategoría.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCategoría.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCategoría.setText("Categoría");
        jPanel1.add(lblTituloCategoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        lblPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioUnitario.setForeground(new java.awt.Color(0, 0, 51));
        lblPrecioUnitario.setText("Precio Unitario");
        jPanel1.add(lblPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        lblTituloStockInicial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockInicial.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockInicial.setText("Stock Inicial");
        jPanel1.add(lblTituloStockInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        lblTituloStockMinimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockMinimo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockMinimo.setText("Stock Mínimo");
        jPanel1.add(lblTituloStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(237, 237, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perecedero", "Electrónico", "Materia Prima" }));
        jComboBox1.setOpaque(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 280, 30));

        txtCodigoProducto.setBackground(new java.awt.Color(237, 237, 255));
        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(0, 0, 51));
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 30));

        txtNombre.setBackground(new java.awt.Color(237, 237, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 30));

        txtProveedor.setBackground(new java.awt.Color(237, 237, 255));
        txtProveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(0, 0, 51));
        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 280, 30));

        jPanelPerecedero.setBackground(new java.awt.Color(0, 0, 0));
        jPanelPerecedero.setForeground(new java.awt.Color(245, 247, 255));
        jPanelPerecedero.setOpaque(false);
        jPanelPerecedero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiasVigencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDiasVigencia.setForeground(new java.awt.Color(0, 0, 51));
        lblDiasVigencia.setText("Días de Vigencia");
        jPanelPerecedero.add(lblDiasVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTemperatura.setForeground(new java.awt.Color(0, 0, 51));
        lblTemperatura.setText("Temperatura (°C)");
        jPanelPerecedero.add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblFechaVencimiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFechaVencimiento.setForeground(new java.awt.Color(0, 0, 51));
        lblFechaVencimiento.setText("Fecha de Vencimiento");
        jPanelPerecedero.add(lblFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jDateChooser.setBackground(new java.awt.Color(237, 237, 255));
        jDateChooser.setForeground(new java.awt.Color(0, 0, 51));
        jPanelPerecedero.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, -1));

        txtDiasVigencia.setBackground(new java.awt.Color(237, 237, 255));
        txtDiasVigencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiasVigencia.setForeground(new java.awt.Color(0, 0, 51));
        txtDiasVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasVigenciaActionPerformed(evt);
            }
        });
        jPanelPerecedero.add(txtDiasVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 30));

        txtTemperatura.setBackground(new java.awt.Color(237, 237, 255));
        txtTemperatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTemperatura.setForeground(new java.awt.Color(0, 0, 51));
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });
        jPanelPerecedero.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        jPanel1.add(jPanelPerecedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, 230));

        jPanelMateriaPrima.setBackground(new java.awt.Color(0, 0, 0));
        jPanelMateriaPrima.setForeground(new java.awt.Color(245, 247, 255));
        jPanelMateriaPrima.setOpaque(false);
        jPanelMateriaPrima.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloUnidadMedida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloUnidadMedida.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloUnidadMedida.setText("Unidad de Medida");
        jPanelMateriaPrima.add(lblTituloUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblTituloConcentracion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloConcentracion.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloConcentracion.setText("Concentración");
        jPanelMateriaPrima.add(lblTituloConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtUnidadMedida.setBackground(new java.awt.Color(237, 237, 255));
        txtUnidadMedida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnidadMedida.setForeground(new java.awt.Color(0, 0, 51));
        txtUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadMedidaActionPerformed(evt);
            }
        });
        jPanelMateriaPrima.add(txtUnidadMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 30));

        txtConcentracion.setBackground(new java.awt.Color(237, 237, 255));
        txtConcentracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConcentracion.setForeground(new java.awt.Color(0, 0, 51));
        txtConcentracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcentracionActionPerformed(evt);
            }
        });
        jPanelMateriaPrima.add(txtConcentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        jPanel1.add(jPanelMateriaPrima, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 310, 230));

        jPanelElectronico.setBackground(new java.awt.Color(0, 0, 0));
        jPanelElectronico.setForeground(new java.awt.Color(245, 247, 255));
        jPanelElectronico.setOpaque(false);
        jPanelElectronico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloNumeroSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloNumeroSerie.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloNumeroSerie.setText("Número de Serie");
        jPanelElectronico.add(lblTituloNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblTituloGarantia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloGarantia.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloGarantia.setText("Garantía (meses)");
        jPanelElectronico.add(lblTituloGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTituloVoltaje.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloVoltaje.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloVoltaje.setText("Voltaje");
        jPanelElectronico.add(lblTituloVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtNumeroSerie.setBackground(new java.awt.Color(237, 237, 255));
        txtNumeroSerie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumeroSerie.setForeground(new java.awt.Color(0, 0, 51));
        txtNumeroSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroSerieActionPerformed(evt);
            }
        });
        jPanelElectronico.add(txtNumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 30));

        txtGarantia.setBackground(new java.awt.Color(237, 237, 255));
        txtGarantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGarantia.setForeground(new java.awt.Color(0, 0, 51));
        txtGarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGarantiaActionPerformed(evt);
            }
        });
        jPanelElectronico.add(txtGarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 30));

        txtVoltaje.setBackground(new java.awt.Color(237, 237, 255));
        txtVoltaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVoltaje.setForeground(new java.awt.Color(0, 0, 51));
        txtVoltaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVoltajeActionPerformed(evt);
            }
        });
        jPanelElectronico.add(txtVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, 30));

        jPanel1.add(jPanelElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 320, 230));

        btnLimpiar.setBackground(new java.awt.Color(237, 237, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 51));
        btnLimpiar.setText("Registrar Nuevo Producto");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 280, -1));

        txtPrecio.setBackground(new java.awt.Color(237, 237, 255));
        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 51));
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 280, 30));

        txtStockInicial.setBackground(new java.awt.Color(237, 237, 255));
        txtStockInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockInicial.setForeground(new java.awt.Color(0, 0, 51));
        txtStockInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockInicialActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 280, 30));

        txtStockMinimo.setBackground(new java.awt.Color(237, 237, 255));
        txtStockMinimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockMinimo.setForeground(new java.awt.Color(0, 0, 51));
        txtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMinimoActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 280, 30));

        btnRegistrar.setBackground(new java.awt.Color(237, 237, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 51));
        btnRegistrar.setText("Registrar Producto");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 280, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPrincipal2.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //atras a izq
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void txtDiasVigenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasVigenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasVigenciaActionPerformed

    private void txtVoltajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVoltajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVoltajeActionPerformed

    private void txtGarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGarantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGarantiaActionPerformed

    private void txtNumeroSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSerieActionPerformed

    private void txtUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadMedidaActionPerformed

    private void txtConcentracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcentracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcentracionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        //limpiar a Registrar nuevo producto
        txtCodigoProducto.setText("");
        txtNombre.setText("");
        txtProveedor.setText("");
        txtPrecio.setText("");
        txtStockInicial.setText("");
        txtStockMinimo.setText("");
        txtTemperatura.setText("");
        txtDiasVigencia.setText("");
        txtNumeroSerie.setText("");
        txtGarantia.setText("");
        txtVoltaje.setText("");
        txtUnidadMedida.setText("");
        txtConcentracion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jPanelPerecedero.setVisible(false);
        jPanelElectronico.setVisible(false);
        jPanelMateriaPrima.setVisible(false);
        if(jComboBox1.getSelectedItem().toString().equals("Perecedero"))
        {
            jPanelPerecedero.setVisible(true);
        }
        else if(jComboBox1.getSelectedItem().toString().equals("Electrónico"))
        {
            jPanelElectronico.setVisible(true);
        }
        else
        {
            jPanelMateriaPrima.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockInicialActionPerformed

    private void txtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockMinimoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        producto registrado correctamente
        ya existe un producto con ese codigo
        datos inválidos
        */
        Date mFecha= jDateChooser.getDate();
        long fecha= mFecha.getTime();
        java.sql.Date fecha_sql= new java.sql.Date(fecha);
        System.out.println("FECHA: "+fecha_sql);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JToggleButton btnRegistrar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelElectronico;
    private javax.swing.JPanel jPanelMateriaPrima;
    private javax.swing.JPanel jPanelPerecedero;
    private javax.swing.JLabel lblDiasVigencia;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblPrecioUnitario;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblTituloCategoría;
    private javax.swing.JLabel lblTituloCodigo;
    private javax.swing.JLabel lblTituloConcentracion;
    private javax.swing.JLabel lblTituloGarantia;
    private javax.swing.JLabel lblTituloNombre;
    private javax.swing.JLabel lblTituloNumeroSerie;
    private javax.swing.JLabel lblTituloProveedor;
    private javax.swing.JLabel lblTituloStockInicial;
    private javax.swing.JLabel lblTituloStockMinimo;
    private javax.swing.JLabel lblTituloUnidadMedida;
    private javax.swing.JLabel lblTituloVoltaje;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtConcentracion;
    private javax.swing.JTextField txtDiasVigencia;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroSerie;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtStockInicial;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtUnidadMedida;
    private javax.swing.JTextField txtVoltaje;
    // End of variables declaration//GEN-END:variables
}
