/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

import java.awt.Color;
import clases.Producto;
import java.awt.Component;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author valer
 */
public class ReportesAlertas extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public ReportesAlertas() {
        initComponents();
        cargarAlertas();
    }

    
    public void cargarAlertas()
    {
        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        List<Producto> productos= AppContext.getGestorInventario().obtenerProductos();
        String fechaActual = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        int totalAlertas = 0;
        String[] grupos = {"CRÍTICO", "BAJO", "PRÓXIMO A VENCER", "OTROS"};
        for (String grupo : grupos)
        {
            for (Producto producto : productos) 
            {
                String alerta = producto.generarAlerta();
                if (alerta == null || alerta.isBlank()) 
                {
                    continue;
                }
                String tipo = clasificarAlerta(producto, alerta);
                if(!tipo.equals(grupo))
                {
                    continue;
                }

                modelo.addRow(new Object[]{
                    producto.getCodigo(),
                    producto.getNombre(),
                    producto.tieneStockCritico() ? "Stock Crítico" : "Activo",
                    alerta,
                    tipo,
                    fechaActual
                });
                totalAlertas++;
            }
        }
        txtTotalAlertasActivas.setText(String.valueOf(totalAlertas));
        UiUtils.ajustarAnchoColumnas(jTable1, jScrollPane1, new int[]{80, 140, 120, 280, 120, 150}, 830);
    }

    private String clasificarAlerta(Producto producto, String alerta)
    {
        if(producto.getStockActual() == 0 || alerta.startsWith("CRITICO"))
        {
            return "CRÍTICO";
        }
        if(producto.tieneStockCritico())
        {
            return "BAJO";
        }
        if(alerta.contains("Vence"))
        {
            return "PRÓXIMO A VENCER";
        }
        return "OTROS";
    }
    /*
    preguntar si aqui ocupan exportar alertas tipo como archivo
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        lblTituloTotalAlertasActivas = new javax.swing.JLabel();
        txtTotalAlertasActivas = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack1 = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnReportes.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        lblTituloTotalAlertasActivas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloTotalAlertasActivas.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTotalAlertasActivas.setText("Total Alertas Activas");
        jPanel1.add(lblTituloTotalAlertasActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        txtTotalAlertasActivas.setEditable(false);
        txtTotalAlertasActivas.setBackground(new java.awt.Color(237, 237, 255));
        txtTotalAlertasActivas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalAlertasActivas.setForeground(new java.awt.Color(0, 0, 51));
        txtTotalAlertasActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAlertasActivasActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalAlertasActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 220, 30));

        btnActualizar.setBackground(new java.awt.Color(237, 237, 255));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 51));
        btnActualizar.setText("Refrescar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 280, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 234));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Estado", "Motivo/Detalle", "Tipo", "Fecha"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(237, 237, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setShowGrid(false);
        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                Component component = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if(!isSelected)
                {
                    String tipo = String.valueOf(table.getValueAt(row, 4));
                    if("CRÍTICO".equals(tipo))
                    {
                        component.setBackground(new Color(255, 224, 224));
                    }
                    else if("BAJO".equals(tipo))
                    {
                        component.setBackground(new Color(255, 244, 204));
                    }
                    else if("PRÓXIMO A VENCER".equals(tipo))
                    {
                        component.setBackground(new Color(229, 242, 255));
                    }
                    else
                    {
                        component.setBackground(new Color(255, 255, 234));
                    }
                    component.setForeground(new Color(0, 0, 0));
                }
                return component;
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 830, 240));

        btnBack1.setBackground(new java.awt.Color(237, 237, 255));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(0, 0, 51));
        btnBack1.setText("Atrás");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal3.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        -salida registrada correctamente
        -stock insuficiente
        */
        cargarAlertas();
        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
        if(modelo.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this, "NO HAY ALERTAS ACTIVAS EN ESTE MOMENTO.", "SIN ALERTAS", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtTotalAlertasActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAlertasActivasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAlertasActivasActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportesAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportesAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportesAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportesAlertas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportesAlertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActualizar;
    private javax.swing.JToggleButton btnBack1;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblTituloTotalAlertasActivas;
    private javax.swing.JTextField txtTotalAlertasActivas;
    // End of variables declaration//GEN-END:variables
}
