/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;

/**
 *
 * @author valer
 */
public class SalidaMercancia extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public SalidaMercancia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        lblTituloCodigo = new javax.swing.JLabel();
        lblTituloCategoria = new javax.swing.JLabel();
        lblTituloCant = new javax.swing.JLabel();
        lblTituloResumen = new javax.swing.JLabel();
        lblPrecioUnitario = new javax.swing.JLabel();
        lblTituloMotivo = new javax.swing.JLabel();
        lblTituloStockAntes = new javax.swing.JLabel();
        lblTituloStockDespues = new javax.swing.JLabel();
        lblTituloStockActual = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtStockActual = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        txtStockAntes = new javax.swing.JTextField();
        txtStockDespues = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();
        btnSalida = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnSalida.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        btnBack.setBackground(new java.awt.Color(237, 237, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 51));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        lblTituloCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCodigo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCodigo.setText("Código Producto");
        jPanel1.add(lblTituloCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        lblTituloCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCategoria.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCategoria.setText("Categoría");
        jPanel1.add(lblTituloCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblTituloCant.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloCant.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloCant.setText("Cantidad a Retirar");
        jPanel1.add(lblTituloCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        lblTituloResumen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloResumen.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloResumen.setText("RESUMEN");
        jPanel1.add(lblTituloResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        lblPrecioUnitario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioUnitario.setForeground(new java.awt.Color(0, 0, 51));
        lblPrecioUnitario.setText("Nombre del Producto");
        jPanel1.add(lblPrecioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));

        lblTituloMotivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloMotivo.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloMotivo.setText("Motivo / Detalle");
        jPanel1.add(lblTituloMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        lblTituloStockAntes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockAntes.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockAntes.setText("Stock Antes");
        jPanel1.add(lblTituloStockAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        lblTituloStockDespues.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockDespues.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockDespues.setText("Stock Después");
        jPanel1.add(lblTituloStockDespues, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 130, -1));

        lblTituloStockActual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloStockActual.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloStockActual.setText("Stock Actual");
        jPanel1.add(lblTituloStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        txtCodigoProducto.setBackground(new java.awt.Color(237, 237, 255));
        txtCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(0, 0, 51));
        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 280, 30));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(237, 237, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 51));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 280, 30));

        txtStockActual.setEditable(false);
        txtStockActual.setBackground(new java.awt.Color(237, 237, 255));
        txtStockActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockActual.setForeground(new java.awt.Color(0, 0, 51));
        txtStockActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockActualActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 280, 30));

        txtCategoria.setEditable(false);
        txtCategoria.setBackground(new java.awt.Color(237, 237, 255));
        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(0, 0, 51));
        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, 30));

        txtCant.setBackground(new java.awt.Color(237, 237, 255));
        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCant.setForeground(new java.awt.Color(0, 0, 51));
        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        jPanel1.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 280, 30));

        txtMotivo.setBackground(new java.awt.Color(237, 237, 255));
        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(0, 0, 51));
        txtMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 280, 30));

        txtStockAntes.setEditable(false);
        txtStockAntes.setBackground(new java.awt.Color(237, 237, 255));
        txtStockAntes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockAntes.setForeground(new java.awt.Color(0, 0, 51));
        txtStockAntes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockAntesActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockAntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 320, 30));

        txtStockDespues.setEditable(false);
        txtStockDespues.setBackground(new java.awt.Color(237, 237, 255));
        txtStockDespues.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStockDespues.setForeground(new java.awt.Color(0, 0, 51));
        txtStockDespues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockDespuesActionPerformed(evt);
            }
        });
        jPanel1.add(txtStockDespues, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 300, 30));

        btnBuscar.setBackground(new java.awt.Color(237, 237, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 51));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 280, -1));

        btnSalida.setBackground(new java.awt.Color(237, 237, 255));
        btnSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(0, 0, 51));
        btnSalida.setText("Registrar Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 280, -1));

        btnLimpiar.setBackground(new java.awt.Color(237, 237, 255));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 51));
        btnLimpiar.setText("Limpiar Casillas de Información");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 280, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoPrincipal2.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void txtStockDespuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockDespuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockDespuesActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtCodigoProducto.setText("");
        txtNombre.setText("");
        txtStockActual.setText("");
        txtCategoria.setText("");
        txtCant.setText("");
        txtMotivo.setText("");
        txtStockAntes.setText("");
        txtStockDespues.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void txtStockActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActualActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        -salida registrada correctamente
        -stock insuficiente
        */
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void txtStockAntesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockAntesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockAntesActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        producto no encontrado
        */
        txtNombre.setText("nombre");
        txtStockActual.setText("Stock actual");
        txtCategoria.setText("categoria");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalidaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalidaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalidaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalidaMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalidaMercancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnLimpiar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JToggleButton btnSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblPrecioUnitario;
    private javax.swing.JLabel lblTituloCant;
    private javax.swing.JLabel lblTituloCategoria;
    private javax.swing.JLabel lblTituloCodigo;
    private javax.swing.JLabel lblTituloMotivo;
    private javax.swing.JLabel lblTituloResumen;
    private javax.swing.JLabel lblTituloStockActual;
    private javax.swing.JLabel lblTituloStockAntes;
    private javax.swing.JLabel lblTituloStockDespues;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStockActual;
    private javax.swing.JTextField txtStockAntes;
    private javax.swing.JTextField txtStockDespues;
    // End of variables declaration//GEN-END:variables
}
