/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menus;
import clases.Producto;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.GestorInventario;
/**
 *
 * @author valer
 */
public class ValorTotalAlmacen extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicio
     */
    public ValorTotalAlmacen() {
        initComponents();
        cargarResumen();
    }

    private void cargarResumen()
    {
        GestorInventario gestorInventario = AppContext.getGestorInventario();
        List<Producto> productos= gestorInventario.obtenerProductos();
        double valorTotal= gestorInventario.calcularValorTotalAlmacen();
        int totalProductos= productos.size();
        int totalUnidades=0;
        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        for (Producto producto : productos) 
        {
            totalUnidades+=producto.getStockActual();
            modelo.addRow(new Object[] {producto.getCodigo(), producto.getNombre(), producto.getStockActual(), String.format("%.2f", producto.calcularValorStock())});
        }
        txtValorTotal.setText(String.format("%.2f", valorTotal));
        txtTotalProductos.setText(String.valueOf(totalProductos));
        txtTotalUnidades.setText(String.valueOf(totalUnidades));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();
        btnRecalcular = new javax.swing.JToggleButton();
        lblTituloValorTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        lblTotalProductos = new javax.swing.JLabel();
        txtTotalProductos = new javax.swing.JTextField();
        lblTituloTotalUnidades = new javax.swing.JLabel();
        txtTotalUnidades = new javax.swing.JTextField();
        lblTituloResumen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBack1 = new javax.swing.JToggleButton();
        lblFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnValor.png"))); // NOI18N
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 520, 50));

        btnBack.setBackground(new java.awt.Color(237, 237, 255));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 51));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        btnRecalcular.setBackground(new java.awt.Color(237, 237, 255));
        btnRecalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRecalcular.setForeground(new java.awt.Color(0, 0, 51));
        btnRecalcular.setText("Refresh");
        btnRecalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 280, -1));

        lblTituloValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloValorTotal.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloValorTotal.setText("Valor Total");
        jPanel1.add(lblTituloValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtValorTotal.setBackground(new java.awt.Color(237, 237, 255));
        txtValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValorTotal.setForeground(new java.awt.Color(0, 0, 51));
        txtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 280, 30));

        lblTotalProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalProductos.setForeground(new java.awt.Color(0, 0, 51));
        lblTotalProductos.setText("Total Productos");
        jPanel1.add(lblTotalProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        txtTotalProductos.setBackground(new java.awt.Color(237, 237, 255));
        txtTotalProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalProductos.setForeground(new java.awt.Color(0, 0, 51));
        txtTotalProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalProductosActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 280, 30));

        lblTituloTotalUnidades.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloTotalUnidades.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloTotalUnidades.setText("Total Unidades");
        jPanel1.add(lblTituloTotalUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        txtTotalUnidades.setBackground(new java.awt.Color(237, 237, 255));
        txtTotalUnidades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotalUnidades.setForeground(new java.awt.Color(0, 0, 51));
        txtTotalUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalUnidadesActionPerformed(evt);
            }
        });
        jPanel1.add(txtTotalUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 280, 30));

        lblTituloResumen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloResumen.setForeground(new java.awt.Color(0, 0, 51));
        lblTituloResumen.setText("RESUMEN GENERAL");
        jPanel1.add(lblTituloResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 234));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Stock", "Valor"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setSelectionBackground(new java.awt.Color(237, 237, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 880, 170));

        btnBack1.setBackground(new java.awt.Color(237, 237, 255));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(0, 0, 51));
        btnBack1.setText("Atrás");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal3.png"))); // NOI18N
        jPanel1.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRecalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecalcularActionPerformed
        // TODO add your handling code here:
        /*
        posibles joptionpane:
        -salida registrada correctamente
        -stock insuficiente
        */
        cargarResumen();
    }//GEN-LAST:event_btnRecalcularActionPerformed

    private void txtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalActionPerformed

    private void txtTotalProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalProductosActionPerformed

    private void txtTotalUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalUnidadesActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicio().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValorTotalAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValorTotalAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValorTotalAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValorTotalAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValorTotalAlmacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton btnBack1;
    private javax.swing.JToggleButton btnRecalcular;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JLabel lblTituloResumen;
    private javax.swing.JLabel lblTituloTotalUnidades;
    private javax.swing.JLabel lblTituloValorTotal;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JTextField txtTotalProductos;
    private javax.swing.JTextField txtTotalUnidades;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
